In [1]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import swat
import nltk
nltk.download("punkt")
pd.set_option('display.max_colwidth',100)

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

# Data Import

In [2]:
df=pd.DataFrame()  
for dirname, _, filenames in os.walk('C:\\Users\\frajoz\\OneDrive - SAS\\Domain\\HealthCare\\DÃ©mos\\CORONAVIRUS\\TWEETS VACCINE'):
    for filename in filenames:
        df1 = pd.read_csv(os.path.join(dirname, filename), delimiter=',')
        df=df.append(df1)
print(df.info())
nrow,ncol=df1.shape
nrow2,ncol2=df.shape
print(f"il y a {nrow} lignes et {ncol} colonnes sur le premier dataframe alors que le tout a {nrow2} lignes et {ncol2} colonnes")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299563 entries, 0 to 299562
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_name         299554 non-null  object
 1   user_location     234662 non-null  object
 2   user_description  282670 non-null  object
 3   user_created      299547 non-null  object
 4   user_followers    299540 non-null  float64
 5   user_friends      299540 non-null  object
 6   user_favourites   299540 non-null  object
 7   user_verified     299540 non-null  object
 8   date              299538 non-null  object
 9   text              299540 non-null  object
 10  hashtags          237915 non-null  object
 11  source            297134 non-null  object
 12  is_retweet        299525 non-null  object
dtypes: float64(1), object(12)
memory usage: 29.7+ MB
None
il y a 299563 lignes et 13 colonnes sur le premier dataframe alors que le tout a 299563 lignes et 13 colonnes

<b> Voici le dÃ©tail de la donnÃ©e </b>

# Sentiment Analysis Python

Il existe un code nlp_test.py qui fait l'apprentissage des sentiments sur des tweets taguÃ©s manuellement. L'objectif est de rÃ©cupÃ©rer un "classifier.classify" permettant de classifier nos tweets en se basant sur les informations apprises

In [3]:
%run "C:\\Users\\frajoz\\Programs\\Scripts\\nlp_test.py"
lemmatizer = WordNetLemmatizer()

df["text_tokens"]=df["text"].apply(lambda x:nltk.word_tokenize(str(x)))
df["text_tokens2"]=df['text_tokens'].apply(lambda x:remove_noise(x,stop_words))
df['Sentiment']=df['text_tokens2'].apply(lambda x:classifier.classify(dict([token, True] for token in x)))
df.head()

[(':)', 3691), (':-)', 701), (':d', 658), ('thanks', 388), ('follow', 357), ('love', 333), ('...', 290), ('good', 283), ('get', 264), ('thank', 253)]

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet,text_tokens,text_tokens2,Sentiment
0,MyNewsNE,Assam,MyNewsNE a dedicated multi-lingual media house from North Eastern India.,24-05-2020 10:18,64.0,11.0,110.0,False,18-08-2020 12:55,Australia to Manufacture Covid-19 Vaccine and give it to the Citizens for free of cost: AFP quot...,['CovidVaccine'],Twitter Web App,False,"[Australia, to, Manufacture, Covid-19, Vaccine, and, give, it, to, the, Citizens, for, free, of,...","[australia, manufacture, covid-19, vaccine, give, citizens, free, cost, afp, quote, prime, minis...",Positive
1,Shubham Gupta,NaN,I will tell about all experiences of my life from my videos hope that you all like the videos ðŸ™‚,14-08-2020 16:42,1.0,17.0,0.0,False,18-08-2020 12:55,#CoronavirusVaccine #CoronaVaccine #CovidVaccine Australia is doing very good https://t.co/kBT7l...,"['CoronavirusVaccine', 'CoronaVaccine', 'CovidVaccine']",Twitter for Android,False,"[#, CoronavirusVaccine, #, CoronaVaccine, #, CovidVaccine, Australia, is, doing, very, good, htt...","[coronavirusvaccine, coronavaccine, covidvaccine, australia, good, http, //t.co/kbt7l6pary]",Positive
2,Journal of Infectiology,NaN,Journal of Infectiology (ISSN 2689-9981) is accepting submissions for an upcoming Volume 3 Issue...,14-12-2017 07:07,143.0,566.0,8.0,False,18-08-2020 12:46,Deaths due to COVID-19 in Affected Countries\nRead More: https://t.co/V8Y3Stu0UW\n@r_piryani @sh...,NaN,Twitter Web App,False,"[Deaths, due, to, COVID-19, in, Affected, Countries, Read, More, :, https, :, //t.co/V8Y3Stu0UW,...","[deaths, due, covid-19, affected, countries, read, http, //t.co/v8y3stu0uw, r_piryani, shitalbha...",Negative
3,Zane,NaN,Fresher than you.,18-09-2019 11:01,29.0,25.0,620.0,False,18-08-2020 12:45,@Team_Subhashree @subhashreesotwe @iamrajchoco Stay safe @subhashreesotwe di &amp; @iamrajchoco ...,NaN,Twitter for Android,False,"[@, Team_Subhashree, @, subhashreesotwe, @, iamrajchoco, Stay, safe, @, subhashreesotwe, di, &, ...","[team_subhashree, subhashreesotwe, iamrajchoco, stay, safe, subhashreesotwe, di, amp, iamrajchoc...",Negative
4,Ann-Maree Oâ€™Connor,"Adelaide, South Australia","Retired university administrator. Melburnian by birth, now living in Adelaide. Look back fondly ...",24-01-2013 14:53,83.0,497.0,10737.0,False,18-08-2020 12:45,@michellegrattan @ConversationEDU This is what passes for leadership in our country: a voucher f...,NaN,Twitter Web App,False,"[@, michellegrattan, @, ConversationEDU, This, is, what, passes, for, leadership, in, our, count...","[michellegrattan, conversationedu, pass, leadership, country, voucher, something, wâ€¦, http, //t....",Positive

In [4]:
df.dropna(subset=['text'],inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 299540 entries, 0 to 299562
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_name         299531 non-null  object
 1   user_location     234647 non-null  object
 2   user_description  282655 non-null  object
 3   user_created      299540 non-null  object
 4   user_followers    299540 non-null  float64
 5   user_friends      299540 non-null  object
 6   user_favourites   299540 non-null  object
 7   user_verified     299540 non-null  object
 8   date              299538 non-null  object
 9   text              299540 non-null  object
 10  hashtags          237915 non-null  object
 11  source            297134 non-null  object
 12  is_retweet        299525 non-null  object
 13  text_tokens       299540 non-null  object
 14  text_tokens2      299540 non-null  object
 15  Sentiment         299540 non-null  object
dtypes: float64(1), object(15)
memory usage: 38.9+ MB

# Sentiment Analysis SAS

In [8]:

%run "C:\\Users\\frajoz\\Programs\\Scripts\\connection.py"
s = connection_CAS("VIYAWAVES","10.255.154.254")

In [9]:
if s.table.tableExists(table="VACCIN_COVID19_SENTIMENT",caslib="Public")==1:
    s.dropTable(name='VACCIN_COVID19_SENTIMENT',caslib='Public')
s.upload_frame(df,casout={'name':'VACCIN_COVID19_PYSENT','caslib':'CASUSER','replace':True})
s.datastep.runcode("data Casuser.VACCIN_COVID19_PYSENT;set CASUSER.VACCIN_COVID19_PYSENT;docid=uuidgen();run;")
s.builtins.loadActionSet(actionSet="sentimentAnalysis") 
s.sentimentAnalysis.applySent(casOut={"name":"VACCIN_COVID19_SENT","caslib":"Public","replace":True},language="English",docId="docid",table={"name":'VACCIN_COVID19_PYSENT',"caslib":"CASUSER"},text="text")
s.table.fetch(table={'name':"VACCIN_COVID19_SENT",'caslib':"Public"},to=3)
s.datastep.runcode("data Public.VACCIN_COVID19_SENTIMENT(promote=yes);merge Casuser.VACCIN_COVID19_PYSENT Public.VACCIN_COVID19_SENT;by docid;rename Sentiment=Python_sent _sentiment_=SAS_sent;if missing(text)=0;run;")
s.table.fetch(table={'name':"VACCIN_COVID19_SENTIMENT",'caslib':"Public"},to=3)
s.table.columnInfo(table={'name':"VACCIN_COVID19_SENTIMENT",'caslib':"Public"})

NOTE: Cloud Analytic Services made the uploaded file available as table VACCIN_COVID19_PYSENT in caslib CASUSER(frajoz).
NOTE: The table VACCIN_COVID19_PYSENT has been created in caslib CASUSER(frajoz) from binary data uploaded to Cloud Analytic Services.
NOTE: Added action set 'sentimentAnalysis'.
NOTE: Cloud Analytic Services promoted table VACCIN_COVID19_SENTIMENT in caslib Public to table VACCIN_COVID19_SENTIMENT in caslib Public.

,Column,Label,ID,Type,RawLength,FormattedLength,Format,NFL,NFD
0,user_name,,1,varchar,134,134,,0,0
1,user_location,,2,varchar,159,159,,0,0
2,user_description,,3,varchar,460,460,,0,0
3,user_created,,4,varchar,19,19,,0,0
4,user_followers,,5,double,8,12,,0,0
5,user_friends,,6,varchar,8,8,,0,0
6,user_favourites,,7,varchar,19,19,,0,0
7,user_verified,,8,varchar,258,258,,0,0
8,date,,9,varchar,70,70,,0,0
9,text,,10,varchar,969,969,,0,0
10,hashtags,,11,varchar,512,512,,0,0
11,source,,12,varchar,36,36,,0,0
12,is_retweet,,13,varchar,5,5,,0,0
13,text_tokens,,14,varchar,1484,1484,,0,0
14,text_tokens2,,15,varchar,1107,1107,,0,0
15,Python_sent,,16,varchar,8,8,,0,0
16,docid,,17,char,200,200,,0,0
17,SAS_sent,Sentiment,18,varchar,8,8,$,0,0
18,_score_,Score,19,double,8,12,BEST,0,0

# Text Scoring

In [10]:
host_connection="VIYAWAVES"
LIB_IN="Public"
table='VACCIN_COVID19_SENTIMENT'
var_text="text"
if host_connection=="RACE":
    caslib_model='Analytics_Project_50733442-4d9b-4125-87a0-a57577ab116f'
    table_model='8a7f0b0477148aed017782729b6d005d_CONCEPT_BINARY'
    table_model_cat='8a7f1eb87738dd3001773df1da520000_CATEGORY_BINARY'
elif host_connection=="VIYAWAVES":
    caslib_model='Analytics_Project_f6f7d9b8-b21b-491c-b01c-04db1a1ed9b4'
    table_model="8a7f0b0477148aed017782729b6d005d_CONCEPT_BINARY"
    table_model_cat='8a7f0b0477148ae801778272a5ca0010_CATEGORY_BINARY'    
    caslib_active_model= 'Analytics_Project_f6f7d9b8-b21b-491c-b01c-04db1a1ed9b4'
    table_active_model='8a7f0b0477148ae801778272a5ca0010_CATEGORY_BINARY'

#TRANSPOSE IN DATAPREP? 
LIB_OUT="Public"


flag_concept='Y'
flag_categ='Y'
flag_fact='Y'
flag_active_learning='Y'

%run "C:\\Users\\frajoz\\Programs\\Scripts\\Scoring_text.py"
scoring_text(host_connection,flag_concept,flag_fact,flag_categ,flag_active_learning,table,var_text,LIB_IN,LIB_OUT,table_model,table_model_cat,caslib_model,table_active_model,caslib_active_model)

ERROR: The table FINC_VACCIN_COVID19_SENTIMENT could not be located in caslib Public of Cloud Analytic Services.
ERROR: The action stopped due to errors.
NOTE: Added action set 'textRuleDevelop'.
NOTE: Added action set 'textRuleScore'.
WARNING: The variable _NAME_ in the DROP, KEEP, or RENAME list has never been referenced.
WARNING: The variable _LABEL_ in the DROP, KEEP, or RENAME list has never been referenced.
NOTE: Duplicate messages output by DATA step:
WARNING: The variable _NAME_ in the DROP, KEEP, or RENAME list has never been referenced.  (occurred 32 times)
WARNING: The variable _LABEL_ in the DROP, KEEP, or RENAME list has never been referenced.  (occurred 32 times)
NOTE: Added action set 'fedSql'.

[Result Set]

        _concept_   COUNT
 0                 296435
 1  C_SIDE_EFFECT    4370

+ Elapsed: 0.386s, user: 0.542s, sys: 0.389s, mem: 137mb

ERROR: The table F_VACCIN_COVID19_SENTIMENT could not be located in caslib CASUSER(frajoz) of Cloud Analytic Services.
ERROR: The action stopped due to errors.
NOTE: Cloud Analytic Services promoted table F_VACCIN_COVID19_SENTIMENT in caslib CASUSER(frajoz) to table F_VACCIN_COVID19_SENTIMENT in caslib CASUSER(frajoz).
NOTE: Table FILTER_F_VACCIN was created in caslib CASUSER(frajoz) with 416 rows returned.
NOTE: Added action set 'transpose'.
NOTE: There were 416 rows read from the table FILTER_F_VACCIN.
NOTE: The table FILTER_F_VACCIN_TRSPOUT has 208 rows and 7 columns.
NOTE: Table C_VACCIN_COVID19_SENTIMENT was created in caslib CASUSER(frajoz) with 300815 rows returned.
NOTE: Cloud Analytic Services saved the file F_VACCIN_COVID19_SENTIMENT.sashdat in caslib CASUSER(frajoz).
NOTE: Added action set 'textRuleDevelop'.
NOTE: Added action set 'textRuleScore'.
NOTE: MERGE statement has more than one data set with repeats of BY values.
NOTE: Duplicate messages output by DATA step:
NOTE: MERGE statement has more than one data set with repeats of BY values.  (occurred 32 times)
NOTE: Added action set 'textRuleDevelop'.
NOTE: Added action set 'textRuleScore'.
NOTE: MERGE statement has more than one data set with repeats of BY values.
NOTE: Duplicate messages output by DATA step:
NOTE: MERGE statement has more than one data set with repeats of BY values.  (occurred 32 times)
NOTE: Cloud Analytic Services saved the file C_VACCIN_COVID19_SENTIMENT.sashdat in caslib CASUSER(frajoz).
NOTE: Cloud Analytic Services made the file C_VACCIN_COVID19_SENTIMENT.sashdat available as table FINC_VACCIN_COVID19_SENTIMENT in caslib Public.

### Croisement entre Labs et Doses (1ere ou 2Ã¨me Dose ? )

In [11]:
s.table.droptable(table='FINC_VACCIN_COVID19_SENTIMENT_NEW',caslib="Public")
s.datastep.runcode("data COVID_DOSE_FILTER;set  Public.FINC_VACCIN_COVID19_SENTIMENT;if scan(_category_,1,'/')='DOSE';DOSE=tranwrd(scan(_category_,2,'/'),'_',' ');run;")
s.builtins.loadActionSet("fedSql")                           #2  

s.fedSql.execDirect(                                    #3 
          query='''create table COVID_DOSE{options replace=true} as select distinct docid,DOSE from COVID_DOSE_FILTER where DOSE is not null'''
        )
s.datastep.runcode("data COVID_DOSE_UNFILTER;set  Public.FINC_VACCIN_COVID19_SENTIMENT;if scan(_category_,1,'/') ne 'DOSE';run;")

s.fedSql.execDirect(                                    #3 
          query='''create table Public.FINC_VACCIN_COVID19_SENTIMENT_NEW{options replace=true} as select t1.*,t2.DOSE from COVID_DOSE_UNFILTER t1 left join COVID_DOSE t2 on t1.docid=t2.docid'''
        )
s.table.promote(table='FINC_VACCIN_COVID19_SENTIMENT_NEW',caslib="Public",targetLib="Public")

ERROR: The table FINC_VACCIN_COVID19_SENTIMENT_NEW could not be located in caslib Public of Cloud Analytic Services.
ERROR: The action stopped due to errors.
NOTE: Added action set 'fedSql'.
NOTE: Table COVID_DOSE was created in caslib CASUSER(frajoz) with 13357 rows returned.
NOTE: Table FINC_VACCIN_COVID19_SENTIMENT_NEW was created in caslib Public with 352989 rows returned.
NOTE: Cloud Analytic Services promoted table FINC_VACCIN_COVID19_SENTIMENT_NEW in caslib Public to table FINC_VACCIN_COVID19_SENTIMENT_NEW in caslib Public.

+ Elapsed: 0.096s, user: 0.00563s, sys: 0.0896s, mem: 0.302mb

In [12]:
s.table.tableinfo(table={'name':'FINC_VACCIN_COVID19_SENTIMENT_NEW','caslib':'Public'})
s.table.save(table={'name':'FINC_VACCIN_COVID19_SENTIMENT_NEW','caslib':'Public'}, name='FINC_VACCIN_COVID19_SENTIMENT_NEW'+'.sashdat',caslib="frcltmp", replace=True)
s.table.save(table={'name':'VACCIN_COVID19_SENTIMENT','caslib':'Public'}, name='VACCIN_COVID19_SENTIMENT'+'.sashdat',caslib="frcltmp", replace=True)

NOTE: Cloud Analytic Services saved the file FINC_VACCIN_COVID19_SENTIMENT_NEW.sashdat in caslib frcltmp.
NOTE: Cloud Analytic Services saved the file VACCIN_COVID19_SENTIMENT.sashdat in caslib frcltmp.

[caslib]

 'frcltmp'

[name]

 'VACCIN_COVID19_SENTIMENT.sashdat'

+ Elapsed: 1.16s, user: 0.229s, sys: 0.41s, mem: 16.3mb

In [ ]:
s.terminate()